apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-depl
  labels:
    app: mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-depl
  strategy: {}
  template:
    metadata:
      labels:
        app: mongo-depl
    spec:
      containers:
        - name: mongo-depl
          image: mongo:latest
          args: ["--dbpath", "/data/db"]
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 27017
          # livenessProbe:
          #   exec:
          #     command:
          #       - mongo
          #       - --disableImplicitSessions
          #       - --eval
          #       - "db.adminCommand('ping')"
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 6
          # readinessProbe:
          #   exec:
          #     command:
          #       - mongo
          #       - --disableImplicitSessions
          #       - --eval
          #       - "db.adminCommand('ping')"
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 6
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
          volumeMounts:
            - name: "mongo-pvc"
              mountPath: "/data/db"
      volumes:
        - name: "mongo-pvc"
          persistentVolumeClaim:
            claimName: "mongo-pvc"

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mongo-client
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mongo-client
#   template:
#     metadata:
#       labels:
#         app: mongo-client
#     spec:
#       containers:
#         - name: mongo-client
#           image: mongo:latest
#           resources:
#             limits:
#               memory: "512Mi"
#               cpu: "500m"
#           ports:
#             - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  selector:
    app: mongo-depl
  ports:
    - name: db
      port: 27017
      targetPort: 27017
      protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data/mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
